services:
    tibillet_docusaurus:
        build: .
        container_name: tibillet_docusaurus
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - USE_SSH=true
            - SSH_AUTH_SOCK=/ssh-agent
        env_file: .env
        volumes:
            - .:/opt/docusaurus
            - ${SSH_AUTH_SOCK}:/ssh-agent
        command: bash dev_start.sh # yarn start --host 0.0.0.0 --locale fr
