services:
    tibillet_docusaurus:
        build: .
        container_name: tibillet_docusaurus
        ports:
            - "3000:3000"
        volumes:
            - .:/opt/docusaurus
        environment:
            - NODE_ENV=development
            - USE_SSH=true
        env_file: .env
        command: bash start.sh
