site_name: TiBillet
site_url: https://tibillet.org

site_dir: site
docs_dir: docs

# nav

nav:
  - index.md
  - Introduction:
    - introduction/uses.md
    - introduction/demonstration.md
    - introduction/philosophy.md
    - introduction/solidarity-based.md
    - introduction/design.md
  - Lespass:
    - lespass/event.md
    - lespass/event-free.md
    - lespass/webhooks.md
    - lespass/embed.md
    - lespass/rss.md
  - Laboutik:
    - laboutik/android.md
    - laboutik/primary-cards.md
    - laboutik/outlets.md
    - laboutik/categories.md
    - laboutik/articles.md
    - laboutik/orders.md
    - laboutik/order-deletion.md
    - laboutik/time-clock.md
    - laboutik/loyalty-points.md
    - laboutik/cashback.md
  # - Fedow:
  #   - fedow.md
  - Standalone install:
    - standalone/self-hosting.md
    - standalone/diy-cashless.md
  - Contributing:
    # - contribution/docs.md
    - contribution/dev.md
  - Resources:
    - resources/design.md
  - API:
    - api/index.md
    - api/keys.md
    - api/tenants.md
    - api/products.md
    - api/events.md
    - api/bookings.md

extra:

  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr

#footer

copyright: CC-BY-SA @ 2024 - SCIC TiBillet Coop

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7FJvtYx
      name: Discord

    - icon: fontawesome/brands/rocketchat
      link: https://chat.tiers-lieux.org/channel/TiBillet
      name: Rocket Chat

    - icon: fontawesome/solid/comments
      link: https://matrix.to/#/#tibillet:tiers-lieux.org
      name: Matrix

    - icon: fontawesome/solid/envelope
      link: mailto:<contact@tibillet.re>
      name: Email

    - icon: fontawesome/brands/github-alt
      link: https://github.com/TiBillet
      name: Github

# theme

theme:
  name: material
  logo: /assets/icon.svg
  favicon: /assets/favicon.svg
  language: en
  custom_dir: theme
  
  palette:

    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  
  features:
    # - navigation.instant
    - navigation.instant.preview
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy

extra_css:
  - /assets/style.css

# plugins

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  # - privacy
  - tags
  - glightbox
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Standalone install: Installation autonome
            Contributing: Contribuer
            Resources: Ressources
          theme:
            language: fr
            
            palette:

              # dark mode
              - media: "(prefers-color-scheme: dark)"
                scheme: slate
                toggle:
                  icon: material/brightness-7
                  name: Passer au thème clair

              # light mode
              - media: "(prefers-color-scheme: light)"
                scheme: default
                toggle:
                  icon: material/brightness-4
                  name: Passer au thème sombre
