#footer

copyright: CC-BY-SA @ 2024 - SCIC TiBillet Coop

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7FJvtYx
      name: Discord

    - icon: fontawesome/brands/rocketchat
      link: https://chat.tiers-lieux.org/channel/TiBillet
      name: Rocket Chat

    - icon: fontawesome/solid/comments
      link: https://matrix.to/#/#tibillet:tiers-lieux.org
      name: Matrix

    - icon: fontawesome/solid/envelope
      link: mailto:<contact@tibillet.re>
      name: Email

    - icon: fontawesome/brands/github-alt
      link: https://github.com/TiBillet
      name: Github

# theme

theme:
  name: material
  logo: /assets/icon.svg
  favicon: /assets/favicon.svg

  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy

extra_css:
  - /assets/style.css

extra_javascript:
  - path: /assets/lang-selector.js
    type: module

# extensions

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
