INHERIT: base.yml

site_name: TiBillet documentation
site_url: https://tibillet.org

site_dir: ../site
docs_dir: ../docs/en

# nav

nav:
  - index.md
  - Introduction:
    - introduction/uses.md
    - introduction/demonstration.md
    - introduction/philosophy.md
    - introduction/solidarity-based.md
    - introduction/design.md
  - Lespass:
    - lespass/event.md
    - lespass/event-free.md
    - lespass/webhooks.md
    - lespass/embed.md
    - lespass/rss.md
  - Laboutik:
    - laboutik/android.md
    - laboutik/primary-cards.md
    - laboutik/outlets.md
    - laboutik/categories.md
    - laboutik/articles.md
    - laboutik/orders.md
    - laboutik/order-deletion.md
    - laboutik/time-clock.md
    - laboutik/loyalty-points.md
    - laboutik/cashback.md
  # - Fedow:
  #   - fedow.md
  - Custom install:
    - admin/self-hosting.md
    - admin/diy-cashless.md
  - Contribution guide:
    - contribution/help-wanted.md
    - contribution/dev-setup.md
  - API:
    - api/index.md
    - api/keys.md
    - api/tenants.md
    - api/products.md
    - api/events.md
    - api/bookings.md

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr

# theme

theme:
  language: en
  custom_dir: ../shared
  
  palette:

    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

# additions

plugins:
  - search:
      lang: en
