INHERIT: base.yml

site_name: TiBillet documentation
site_url: https://tibillet.org

site_dir: ../site
docs_dir: ../docs/en

# lang selector

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr

# theme

theme:
  language: en
  custom_dir: ../shared
  
  palette:

    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

# additions

plugins:
  - search:
      lang: en
